# Generated by Django 5.2 on 2025-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Blood Donor'), ('patient', 'Patient'), ('admin', 'Admin')], max_length=10),
        ),
    ]
