# Generated by Django 5.2 on 2025-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_has_medical_conditions_user_has_recent_tattoos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_medical_conditions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_recent_tattoos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_healthy',
        ),
        migrations.AddField(
            model_name='user',
            name='medical_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
